Update README.txt
Correcting the dotnet fsi command to avoid getting: PastrySimulator.fsx(4,1): error FS3302: The package management feature requires language version 5.0 use /langversion:preview
output now looks as follows:
PS C:\Users\prajw\f#Projects\project3> dotnet fsi --langversion:preview .\project3.fsx 32 10
Starting Pastry simulation for numNodes = 32 numRequests = 10
Starting primary routing...
Network has been built!!! Waiting for requests....
Started the routing now.....We will keep you posted with the progress!
We have finished 10 percent of the routing
We have finished 20 percent of the routing
We have finished 30 percent of the routing
We have finished 40 percent of the routing
We have finished 50 percent of the routing
We have finished 60 percent of the routing
We have finished 70 percent of the routing
We have finished 80 percent of the routing
We have finished 90 percent of the routing
We have finished 100 percent of the routing


---------------------------------
Total Routes = 320 Total Hops = 512
Average hops per route = 1.600000
---------------------------------
Total time elapsed is given by 1097.218200 milliseconds